FROM python:3.11-slim

WORKDIR /locust

RUN pip install locust beautifulsoup4

COPY locustfile.py .

EXPOSE 8089

CMD ["locust", "--host=https://snapview-snapview.apps.okd.fured.cloud.bme.hu", "--web-port=8089", "--web-host=0.0.0.0"]